blog/urls.py
from django.urls import path

from blog.views import IndexView, NewCommentView, NewPostView, PostView

urlpatterns = [
    path('posts', IndexView.as_view(), name='blog-index'),
    path('posts/<int:pk>', PostView.as_view(), name='blog-post'),
    path('posts/new', NewPostView.as_view(), name='blog-new-post'),
    path('comment/new', NewCommentView.as_view(), name='blog-new-comment'),
]

users/urls.py
from django.urls import path, include

from users.views import ProfileView

urlpatterns = [
    path('registration/', include('django.contrib.auth.urls')),
    path('<int:pk>/profile', ProfileView.as_view(), name='profile'),
]

yablog_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('yaurl/', include('yaurl.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

yaurl/urls.py
from django.urls import path

from yaurl import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('remove/', views.remove, name='remove'),
    path('redirect/<shorted_id>/', views.shorted_url_redirect, name='redirect'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField('Title', max_length=128)
    content = models.TextField('Content')
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField('Created At', auto_now=True)

    def __str__(self):
        return f'{self.author.username} - {self.title}'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=1)
    content = models.TextField('Content')
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField('Created At', auto_now=True)

    def __str__(self):
        return f'{self.post.title} - Comment by {self.author.username}'

users/models.py
# Create your models here.

yaurl/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class ShortedUrl(models.Model):
    original_url = models.CharField('Original URL', max_length=512)
    redirects = models.IntegerField('Redirects', default=0)
    created_at = models.DateTimeField('Created At')

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.original_url

blog/forms.py
from django import forms


class PostForm(forms.Form):
    title = forms.CharField(max_length=128)
    content = forms.CharField(widget=forms.Textarea())


class CommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea())
    post = forms.IntegerField(widget=forms.HiddenInput())

yaurl/forms.py
from django import forms


class ShortedUrlForm(forms.Form):
    original_url = forms.URLField(label='Original URL', max_length=200)


class RemoveShortedUrlForm(forms.Form):
    shorted_id = forms.IntegerField()

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
# Create your views here.
from django.urls import reverse
from django.views.generic import DetailView, FormView, ListView
from django.views.generic.edit import FormMixin

from blog.forms import CommentForm, PostForm
from blog.models import Comment, Post


class IndexView(FormMixin, ListView):
    template_name = 'blog/index.html'
    paginate_by = 2
    model = Post

    form_class = PostForm


class PostView(FormMixin, DetailView):
    template_name = 'blog/post.html'
    model = Post

    form_class = CommentForm

    def get_initial(self):
        return {'post': self.kwargs['pk']}


class NewPostView(LoginRequiredMixin, FormView):
    template_name = 'blog/new_post.html'
    form_class = PostForm

    def form_valid(self, form):
        post = Post(
            title=form.cleaned_data['title'],
            content=form.cleaned_data['content'],
            author=self.request.user,
        )
        post.save()
        return redirect(reverse('blog-post', kwargs={'pk': post.id}))


class NewCommentView(LoginRequiredMixin, FormView):
    form_class = CommentForm

    def form_valid(self, form):
        comment = Comment(
            content=form.cleaned_data['content'],
            post=get_object_or_404(Post, pk=form.cleaned_data['post']),
            author=self.request.user,
        )
        comment.save()
        return redirect(reverse('blog-post', kwargs={'pk': comment.post.id}))

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
# Create your views here.
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin


class ProfileView(LoginRequiredMixin, SingleObjectMixin, ListView):
    template_name = 'users/profile.html'
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(User.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.object
        return context

    def get_queryset(self):
        return self.object.post_set.all()

yaurl/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
# Create your views here.
from django.urls import reverse
from django.utils import timezone

from yaurl.forms import ShortedUrlForm, RemoveShortedUrlForm
from yaurl.models import ShortedUrl


def index(req):
    shorted_url_form = ShortedUrlForm()
    available_shorts = ShortedUrl.objects.all()
    return render(req, 'yaurl/index.html', {
        'shorted_url_form': shorted_url_form,
        'shorted_urls': sorted(available_shorts,
                               key=lambda short: short.created_at,
                               reverse=True),
    })


@login_required()
def add(req):
    form = ShortedUrlForm(req.POST)
    if form.is_valid():
        new_shorted_url = ShortedUrl(
            original_url=form.cleaned_data['original_url'],
            created_at=timezone.now(),
            user=req.user)
        new_shorted_url.save()
    return redirect(reverse('index'))


@login_required()
def remove(req):
    form = RemoveShortedUrlForm(req.POST)
    if form.is_valid():
        short = get_object_or_404(ShortedUrl, pk=form.cleaned_data['shorted_id'])
        if short.user != req.user:
            return HttpResponseForbidden('!')
        short.delete()
    return redirect(reverse('profile'))


def shorted_url_redirect(req, shorted_id):
    shorted_url = get_object_or_404(ShortedUrl, pk=shorted_id)
    shorted_url.redirects = F('redirects') + 1
    shorted_url.save()
    return redirect(shorted_url.original_url)

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Yablog</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #2f1e39">
        <a class="navbar-brand" href="{% url 'blog-index' %}">Yablog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog-index' %}">Posts <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Yaurl</a>
                </li>
            </ul>
            <ul class="navbar-nav mt-2 mt-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'blog-new-post' %}" class="nav-link text-light">New post</a></li>
                <li class="nav-item"><a href="{% url 'profile' user.id %}" class="nav-link">{{user.username}}</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block 'content' %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/index.html
{% extends 'base.html' %}

<!doctype html>
<html lang="en">

<head>
    <title>Yablog</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .text-limited {
            overflow: hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 5;
            /* number of lines to show */
            -webkit-box-orient: vertical;
        }
    </style>
</head>

<body>
    {% block 'content' %}

    <div class="container mt-4">
        <h2>Posts</h2>
        {% include 'blog/post_list.html' with posts_page=page_obj %}
    </div>

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/new_post.html
{% extends 'base.html' %}

{% block 'content' %}

<div class="container mt-4">
    <form action="{% url 'blog-new-post' %}" method="post">
        {% csrf_token %}    
        <div class="form-group">
            {% include 'form_errors.html' with field=form.title %}

            <label for="{{ form.title.id_for_label }}">Post title</label>
            <input type="text" name="{{ form.title.name }}" id="{{ form.title.id_for_label }}" class="form-control" placeholder="Title" aria-describedby="title">
            <small id="title" class="text-muted">Use interesting title</small>
        </div>
        <div class="form-group">
            {% include 'form_errors.html' with field=form.content %}

            <label for="{{ form.content.id_for_label }}">Post content</label>
            <textarea class="form-control" name="{{ form.content.name }}" id="{{ form.content.id_for_label }}" rows="10"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock 'content' %}

blog/templates/blog/pager.html
<nav aria-label="Page navigation"
    class="d-flex justify-content-center mt-3">
    <ul class="pagination">
        
        <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
            <a class="page-link" href="?page=1">First</a>
        </li>

        {% for page_num in page.paginator.page_range %}
        <li class="page-item {% if page.number == page_num %}active{% endif %}">
            <a class="page-link" href="?page={{page_num}}">{{page_num}}</a>
        </li>
        {% endfor %}

        <li class="page-item {% if not page.has_next %}disabled{% endif %}">
            <a class="page-link" href="?page={{page.paginator.num_pages}}">Last</a>
        </li> 
    </ul>
</nav>

blog/templates/blog/post.html
{% extends 'base.html' %}


{% block 'content' %}

<div class="container mt-4">
    <h2>Post</h2>
    <div class="post">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{post.title}}</h4>
                <p class="card-text">
                    <a class="text-muted" href="{% url 'profile' post.author.id %}">
                        {{post.author.username}}
                    </a>
                </p>
                <p class="card-text">{{post.content}}</p>
            </div>
        </div>
    </div>

    <div class="comments container mt-4">
        <h4>Comment section</h4>

        {% if user.is_authenticated %}

        <form action="{% url 'blog-new-comment' %}" method="post" id="new-comment">
            {% csrf_token %}
            {{ form.post }}
            <div class="card">
                <div class="card-body">
                    <p class="card-text">
                        <a class="text-muted" href="{% url 'profile' user.id %}">
                            {{ user.username }}
                        </a>
                    </p>
                    <p class="card-text">
                        <div class="form-group">
                          <label for="{{ form.content.id_for_label }}">Comment</label>
                          <textarea class="form-control" name="{{ form.content.name }}" id="{{ form.content.id_for_label }}" rows="4"></textarea>
                        </div>
                    </p>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>

        {% endif %}

        {% for comment in post.comment_set.all %}

        <div class="card mt-2">
            <div class="card-body">
                <p class="card-text">
                    <a class="text-muted" href="{% url 'profile' comment.author.id %}">
                        {{comment.author.username}}
                    </a>
                </p>
                <p class="card-text">{{comment.content}}</p>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
<div class="posts">
    {% for post in posts_page %}

    <div class="card mt-2">
        <div class="card-body">
            <h4 class="card-title"><a href="{% url 'blog-post' post.id %}">{{post.title}}</a></h4>
            <p class="card-text">
                <a class="text-muted" href="{% url 'profile' post.author.id %}">
                    {{post.author.username}}
                </a>
            </p>
            <p class="card-text text-limited">{{post.content}}</p>
        </div>
    </div>

    {% endfor %}

    {% include 'blog/pager.html' with page=posts_page %}
</div>

blog/templates/form_errors.html
{% if field.errors %}
{% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
{% endfor %}
{% endif %}

users/templates/users/profile.html
{% extends 'base.html' %}

<!doctype html>
<html lang="en">

<head>
    <title>Yablog</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .text-limited {
            overflow: hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 5;
            /* number of lines to show */
            -webkit-box-orient: vertical;
        }
    </style>
</head>

<body>
    {% block 'content' %}

    <div class="container mt-4">
        <h2>Posts of {{user.username}}</h2>
        {% include 'blog/post_list.html' with posts_page=page_obj %}
    </div>

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

yaurl/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Yaurl Django</title>
</head>
<body>

<nav>
    {% if user.is_authenticated %}
    <p>You are logged in as {{ user.get_username }}</p>
    <a href="{% url 'profile' %}">Profile</a>
    {% else %}
    <p>You aren't logged in</p>
    {% endif %}

    <a href="{% url 'index' %}">Yaurl</a>
    <a href="{% url 'blog-index' %}">Posts</a>
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'logout' %}">Logout</a>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

yaurl/templates/yaurl/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome</h1>

{% if user.is_authenticated %}
<form action="{% url 'add' %}" method="post">
    {% csrf_token %}
    {{ shorted_url_form }}
    <input type="submit" value="Short it!">
</form>
{% endif %}

<h3>Available shorts:</h3>
<table style="width: 40%;">
    <thead>
    <tr>
        <th>Original URL</th>
        <th>Redirects</th>
        <th>Created At</th>
        <th>Author</th>
    </tr>
    </thead>
    <tbody>
    {% for shorted_url in shorted_urls %}
    <tr>
        <td><a href="{% url 'redirect' shorted_url.id %}">{{ shorted_url.original_url }}</a></td>
        <td>{{ shorted_url.redirects }}</td>
        <td>{{ shorted_url.created_at }}</td>
        <td>{{ shorted_url.user.get_username }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}